#!/bin/bash
bib2bib -ob cjenkins_dissertation.bib -c 'category : "dissertation"' cjenkins_self.bib 
bibtex2html -d -nodoc -noheader -r -t "Doctoral Dissertation" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_dissertation.bib
bib2bib -ob cjenkins_chapters.bib -c 'category : "book chapter"' cjenkins_self.bib 
bibtex2html -d -nodoc -noheader -r -t "Book Chapters" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_chapters.bib
bib2bib -ob cjenkins_journal.bib -c 'category : "journal"' cjenkins_self.bib 
bibtex2html -d -nodoc -noheader -r -t "Journal Publications" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_journal.bib
bib2bib -ob cjenkins_magazine.bib  -c 'category : "magazine"' cjenkins_self.bib 
bibtex2html -d -nodoc -noheader -r -t "Non-refereed Journal/Magazine Articles" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_magazine.bib
bib2bib -ob cjenkins_confpaper.bib -c 'category : "conference papers"' cjenkins_self.bib 
bibtex2html -d -nodoc -noheader -r -t "Conference Papers" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_confpaper.bib
bib2bib -ob cjenkins_workshop.bib -c 'category : "workshop"' cjenkins_self.bib 
bibtex2html -d -nodoc -noheader -r -t "Symposia and Workshop Papers" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_workshop.bib
bib2bib -ob cjenkins_confposter.bib -c 'category : "conference posters"' cjenkins_self.bib 
bibtex2html -d -nodoc -noheader -r -t "Conference Posters" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_confposter.bib
bib2bib -ob cjenkins_techreport.bib -c 'category : "technical report"' cjenkins_self.bib 
bibtex2html -d -nodoc -noheader -r -t "Technical Reports" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_techreport.bib
cat pubpageheader.html cjenkins_dissertation.html cjenkins_chapters.html cjenkins_journal.html  cjenkins_magazine.html cjenkins_confpaper.html cjenkins_confposter.html cjenkins_workshop.html cjenkins_techreport.html > cjenkins_publications.html
sed -e 's/^.*filliatr.*$/-->/g' -e 's/^.*has been generated by.*$/<\/table><!--/g' -e 's/h1>/h2>/g' cjenkins_publications.html > delme.html
mv -f delme.html cjenkins_publications.html
cp cjenkins_publications.html /u/cjenkins/www/publications/index_category.shtml
cp cjenkins*bib.html /u/cjenkins/www/publications/

bib2bib -ob cjenkins_2010.bib -c 'year=2010' cjenkins_dissertation.bib cjenkins_chapters.bib cjenkins_journal.bib cjenkins_magazine.bib cjenkins_confpaper.bib cjenkins_confposter.bib cjenkins_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2010" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_2010.bib
bib2bib -ob cjenkins_2009.bib -c 'year=2009' cjenkins_dissertation.bib cjenkins_chapters.bib cjenkins_journal.bib cjenkins_magazine.bib cjenkins_confpaper.bib cjenkins_confposter.bib cjenkins_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2009" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_2009.bib
bib2bib -ob cjenkins_2008.bib -c 'year=2008' cjenkins_dissertation.bib cjenkins_chapters.bib cjenkins_journal.bib cjenkins_magazine.bib cjenkins_confpaper.bib cjenkins_confposter.bib cjenkins_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2008" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_2008.bib
bib2bib -ob cjenkins_2007.bib -c 'year=2007' cjenkins_dissertation.bib cjenkins_chapters.bib cjenkins_journal.bib cjenkins_magazine.bib cjenkins_confpaper.bib cjenkins_confposter.bib cjenkins_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2007" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_2007.bib
bib2bib -ob cjenkins_2006.bib -c 'year=2006' cjenkins_dissertation.bib cjenkins_chapters.bib cjenkins_journal.bib cjenkins_magazine.bib cjenkins_confpaper.bib cjenkins_confposter.bib cjenkins_workshop.bib  
bibtex2html -d -nodoc -noheader -r -t "2006" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_2006.bib
bib2bib -ob cjenkins_2005.bib -c 'year=2005' cjenkins_dissertation.bib cjenkins_chapters.bib cjenkins_journal.bib cjenkins_magazine.bib cjenkins_confpaper.bib cjenkins_confposter.bib cjenkins_workshop.bib   
bibtex2html -d -nodoc -noheader -r -t "2005" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_2005.bib
bib2bib -ob cjenkins_2004.bib -c 'year=2004' cjenkins_dissertation.bib cjenkins_chapters.bib cjenkins_journal.bib cjenkins_magazine.bib cjenkins_confpaper.bib cjenkins_confposter.bib cjenkins_workshop.bib
bibtex2html -d -nodoc -noheader -r -t "2004" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_2004.bib
bib2bib -ob cjenkins_2003.bib -c 'year=2003' cjenkins_dissertation.bib cjenkins_chapters.bib cjenkins_journal.bib cjenkins_magazine.bib cjenkins_confpaper.bib cjenkins_confposter.bib cjenkins_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2003" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_2003.bib
bib2bib -ob cjenkins_2002.bib -c 'year=2002' cjenkins_dissertation.bib cjenkins_chapters.bib cjenkins_journal.bib cjenkins_magazine.bib cjenkins_confpaper.bib cjenkins_confposter.bib cjenkins_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2002" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_2002.bib
bib2bib -ob cjenkins_2001.bib -c 'year=2001' cjenkins_dissertation.bib cjenkins_chapters.bib cjenkins_journal.bib cjenkins_magazine.bib cjenkins_confpaper.bib cjenkins_confposter.bib cjenkins_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2001" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_2001.bib
bib2bib -ob cjenkins_2000.bib -c 'year=2000' cjenkins_dissertation.bib cjenkins_chapters.bib cjenkins_journal.bib cjenkins_magazine.bib cjenkins_confpaper.bib cjenkins_confposter.bib cjenkins_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2000" -s "abbrv" -css "http://www.cs.brown.edu/~cjenkins/default.css" cjenkins_2000.bib
cat pubpageheader.html cjenkins_2009.html cjenkins_2008.html cjenkins_2007.html cjenkins_2006.html cjenkins_2005.html cjenkins_2004.html cjenkins_2003.html cjenkins_2002.html cjenkins_2001.html cjenkins_2000.html > cjenkins_publications_byyear.html
sed -e 's/^.*filliatr.*$/-->/g' -e 's/^.*file was generated by.*$/<\/table><!--/g' -e 's/h1>/h2>/g' cjenkins_publications_byyear.html > delme.html
mv -f delme.html cjenkins_publications_byyear.html
cp cjenkins_publications_byyear.html /u/cjenkins/www/publications/index_year.shtml
cp cjenkins*bib.html /u/cjenkins/www/publications/

ln -s /u/cjenkins/www/publications/index_year.shtml index.shtml
webupdate ~/www/publications/*
webupdate ~/www/papers/*
