#!/bin/bash
bib2bib -ob rlab_dissertation.bib -c 'category : "dissertation"' ../papers/rlab.bib 
bibtex2html -d -nodoc -noheader -r -t "Doctoral Dissertations" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_dissertation.bib
bib2bib -ob rlab_chapters.bib -c 'category : "book chapter"' ../papers/rlab.bib 
bibtex2html -d -nodoc -noheader -r -t "Book Chapters" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_chapters.bib
bib2bib -ob ../papers/rlab_journal.bib -c 'category : "journal"' ../papers/rlab.bib 
bibtex2html -d -nodoc -noheader -r -t "Journal Publications" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_journal.bib
bib2bib -ob ../papers/rlab_magazine.bib  -c 'category : "magazine"' ../papers/rlab.bib 
bibtex2html -d -nodoc -noheader -r -t "Non-refereed Journal/Magazine Articles" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_magazine.bib
bib2bib -ob ../papers/rlab_confpaper.bib -c 'category : "conference papers"' ../papers/rlab.bib 
bibtex2html -d -nodoc -noheader -r -t "Conference Papers" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_confpaper.bib
bib2bib -ob ../papers/rlab_workshop.bib -c 'category : "workshop"' ../papers/rlab.bib 
bibtex2html -d -nodoc -noheader -r -t "Symposia and Workshop Papers" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_workshop.bib
bib2bib -ob ../papers/rlab_confposter.bib -c 'category : "conference posters"' ../papers/rlab.bib 
bibtex2html -d -nodoc -noheader -r -t "Conference Posters" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_confposter.bib
bib2bib -ob ../papers/rlab_techreport.bib -c 'category : "technical report"' ../papers/r0lab.bib 
bibtex2html -d -nodoc -noheader -r -t "Technical Reports" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_techreport.bib
cat pubpageheader.html ../papers/rlab_dissertation.html ../papers/rlab_chapters.html ../papers/rlab_journal.html  ../papers/rlab_magazine.html ../papers/rlab_confpaper.html ../papers/rlab_confposter.html ../papers/rlab_workshop.html ../papers/rlab_techreport.html > ../papers/rlab_publications.html
sed -e 's/^.*filliatr.*$/-->/g' -e 's/^.*file was generated by.*$/<\/table><!--/g' -e 's/h1>/h2>/g' ../papers/rlab_publications.html > delme.html
mv -f delme.html ../papers/rlab_publications.html
#cp ../papers/rlab_publications.html /pro/rlab/www-robotics/publications/index_category.shtml
#cp rlab*bib.html /pro/rlab/www-robotics/publications/

bib2bib -ob ../papers/rlab_2011.bib -c 'year=2011' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2011" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2011.bib
bib2bib -ob ../papers/rlab_2010.bib -c 'year=2010' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2010" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2010.bib
bib2bib -ob ../papers/rlab_2009.bib -c 'year=2009' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2009" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2009.bib
bib2bib -ob ../papers/rlab_2008.bib -c 'year=2008' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2008" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2008.bib
bib2bib -ob ../papers/rlab_2007.bib -c 'year=2007' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2007" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2007.bib
bib2bib -ob ../papers/rlab_2006.bib -c 'year=2006' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2006" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2006.bib
bib2bib -ob ../papers/rlab_2005.bib -c 'year=2005' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2005" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2005.bib
bib2bib -ob ../papers/rlab_2004.bib -c 'year=2004' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2004" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2004.bib
bib2bib -ob ../papers/rlab_2003.bib -c 'year=2003' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2003" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2003.bib
bib2bib -ob ../papers/rlab_2002.bib -c 'year=2002' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2002" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2002.bib
bib2bib -ob ../papers/rlab_2001.bib -c 'year=2001' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2001" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2001.bib
bib2bib -ob ../papers/rlab_2000.bib -c 'year=2000' ../papers/rlab_dissertation.bib ../papers/rlab_chapters.bib ../papers/rlab_journal.bib ../papers/rlab_magazine.bib ../papers/rlab_confpaper.bib ../papers/rlab_confposter.bib ../papers/rlab_workshop.bib 
bibtex2html -d -nodoc -noheader -r -t "2000" -s "abbrv" -css "http://robotics.cs.brown.edu/default.css" ../papers/rlab_2000.bib
cat pubpageheader.html ../papers/rlab_2011.html ../papers/rlab_2010.html ../papers/rlab_2009.html ../papers/rlab_2008.html ../papers/rlab_2007.html ../papers/rlab_2006.html ../papers/rlab_2005.html ../papers/rlab_2004.html ../papers/rlab_2003.html ../papers/rlab_2002.html ../papers/rlab_2001.html ../papers/rlab_2000.html > ../papers/rlab_publications_byyear.html
sed -e 's/^.*filliatr.*$/-->/g' -e 's/^.*file was generated by.*$/<\/table><!--/g' -e 's/h1>/h2>/g' ../papers/rlab_publications_byyear.html > delme.html
mv -f delme.html ../papers/rlab_publications_byyear.html
#cp rlab_publications_byyear.html /pro/rlab/www-robotics/publications/index_year.shtml
#cp rlab_publications_byyear.html /pro/rlab/www-robotics/publications/index_second.html
#cp rlab*bib.html /pro/rlab/www-robotics/publications/

#ln -s /pro/rlab/www-robotics/publications/index_year.shtml index_second.shtml
#webupdate /pro/rlab/www-robotics/publications/*
